name: Deploy to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: 
      - homepages
        
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:

    # uses GitHub's checkout action to checkout code from the homepages branch
    - uses: actions/checkout@v2.3.1
      with:
        ref: homepages
        # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        persist-credentials: false

    # sets up .NET Core SDK 5.0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.200

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish src/gh-pages/gh-pages.csproj -c Release -o release --nologo
    
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
